import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { InquiryCartProvider } from "./context/InquiryCartContext";
import { InquiryCartButton } from "@/components/InquiryCartButton/InquiryCartButton"; // Import the button

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InquiryCartProvider>
          {children}
          <InquiryCartButton /> {/* Add the floating inquiry cart button */}
        </InquiryCartProvider>
      </body>
    </html>
  );
}
